sudo: false
language: node_js
node_js:
- '8'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJMHXAMOFLZBN3GOA
  - secure: gbFaYubi/nnm85tYEK1SrSp9mkgWGwilkqyDenpJEb7Lx7DzDI/ZVNc7afv7Q9Yg4EVMFoG2Eqgzpr/hcpBBql+AXenXDLmbJ2e4TWiBC5gNh4bzIzoeYkakL5c9RckIb5AqXB8zkhsi4MmwP3Gg2fU2tcwsPdAqJxTnFh0DAG/OEo/ip1BgNnThPs8I3X8J+Fi4FvDx1Qd3EEJ24TdUZiK18mvVT7lk5Yq36hpE7sSXdbAW439HtNV0jlMtIWJaZ6awId10FYCMxlwcirUuz9A216BXq2bkAZTw1lB0NPlqondbe+MmycQWftblx7xuly2XYSGs8sGqdj4pQ5ofd59b2U8ZbiQx1/L3oqQX3GhAvT2vMSdBRyoeBdnUm/cQdNHjYI6IhBRaGsmYlEtP6JJNrSOSNSGmHXJ6AchGQ+nTyZC5S19/otn3dx0ZU5+zanOxyb9RANF8XpZcOVjDqWFFjoejTT5KfXHmYjWfuSBUKMZ2lxYQmF9TeK33FW30yAHWlao33mCDIaHS6vMAEts+TjcxdrYh8Eg/mL9VhyNns/tzt4oztvItxmbW2pwQbWJ2VACcGI96qdo/qLjjBLJ1OYq0ySTlY30WiSQFOhGDab3O4mPbzUdbJiPv7006KPxiDJQ264V1jwglURmRFTgiINyT9ahRM6N80mPg0mk=
install:
- yarn
script:
- yarn lint
before_deploy:
- yarn build
- pip install --user awscli
- ls -l
deploy:
  skip_cleanup: true
  provider: script
  script: ls -l && aws s3 sync ./dist s3://scwood-habit-tracker --delete --acl public-read
  on:
    branch:  travis
